rm(list=ls())
data<-read.table("household_power_consumption.txt",header=TRUE,sep=";")
data[,1]<-dmy(data[,1])
data[,2]<-hms(data[,2])
date1<-dmy("01-02-2007")
date2<-dmy("02-02-2007")
data1<-data[data[,1]==date1 | data[,1]==date2,]
Power<-as.numeric(as.character(data1[,3]))
dev.off()
hist(Power,col='red',main="Global Active Power",xlab="Global Active Power (kilowatts)",ylim=c(0,1200))
dev.copy(png,file="plot1.png")
dev.off()