rm(list=ls())
data<-read.table("household_power_consumption.txt",header=TRUE,sep=";")
data[,1]<-dmy(data[,1])
data[,2]<-hms(data[,2])
date1<-dmy("01-02-2007")
date2<-dmy("02-02-2007")
data1<-data[data[,1]==date1 | data[,1]==date2,]
DateTime<-data1[,1]+data1[,2]
data2<-cbind(DateTime,data1)
Sub_metering_1<-as.numeric(as.character(data2[,8]))
Sub_metering_2<-as.numeric(as.character(data2[,9]))
Sub_metering_3<-as.numeric(as.character(data2[,10]))
plot(DateTime,Sub_metering_1,type='l',xlab="",ylab="Energy sub metering",col='black')
lines(DateTime,Sub_metering_2,col='red')
lines(DateTime,Sub_metering_3,col='blue')
dev.copy(png,file="plot3.png")
dev.off()